config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :timelines do
    collection do
      post :confirm
    end
  end
  resources :sessions, only:[:new,:create,:destroy]
  resources :users, only: [:new, :create, :show,:edit,:update]
  resources :relationships, only: [:index,:create,:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :friend, class_name: "User" 
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { in: 1..20 }
  validates :content, presence: true, length: { in: 1..200 }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

  #アソシエーション
  has_many :timelines

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "user_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "friend_id",
                                  dependent: :destroy

  has_many :friend, through: :active_relationships,source: :friend

  #Validationの追加
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true,  uniqueness: true, length: {maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }

  #Image
  mount_uploader :image, ImageUploader

  # 友達追加
  def be_friend(other_user)
     active_relationships.create(friend_id: other_user.id)
     passive_relationships.create(user_id: other_user.id)
  end

  #友達解除する
 def un_friend(other_user)
   active_relationships.find_by(friend_id: other_user.id).destroy
   passive_relationships.find_by(user_id: other_user.id).destroy
 end

 # 現在のユーザーが友達だったらtrueを返す
 def friend?(other_user)
   friend.include?(other_user)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  # ログインチェック
  before_action :login_required

  private

  def login_required
    unless current_user
      flash[:notice] = 'ログインが必要です。'
       redirect_to new_session_path unless current_user
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.find(params[:id])
    current_user.be_friend(@user)
    redirect_to relationships_path
  end

  def destroy
    @user = User.find(params[:id])
    current_user.un_friend(@user)
    redirect_to relationships_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :set_timeline, only: [:edit, :update, :destroy]
  before_action :user_check, only: [:edit,:update,:destroy]

  def index
    @timelines = Timeline.all.order(created_at: "DESC")
  end

  def show
    @timeline = Timeline.find(params[:id])
  end

  def new
    if params[:back]
      @timeline = current_user.timelines.build(timeline_params)
    else
      @timeline = Timeline.new
    end
  end

  def edit
  end

  def create
    @timeline = current_user.timelines.build(timeline_params)
    if @timeline.save
      redirect_to timelines_path, notice: "タイムラインを投稿しました！"
    else
      render action: :new
    end
  end

  def update
    if @timeline.update(timeline_params)
      redirect_to timelines_path, notice: "タイムラインを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @timeline.destroy
    redirect_to timelines_path, notice:"タイムラインを削除しました！"
  end

  def confirm
    @timeline = current_user.timelines.build(timeline_params)
    render :new if @timeline.invalid?
  end

  private

  def set_timeline
    @timeline = current_user.timelines.find(params[:id])
  end

  def timeline_params
    params.require(:timeline).permit(:title, :content, :image,:image_cache)
  end

    #timelineを投稿したユーザとログインユーザが同一でない場合はトップページに戻るTrueを返す
  def user_check
    unless @timeline.user.id == current_user.id
      flash[:notice] = '編集・削除できません'
      redirect_to timelines_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_find, only: [:show,:edit,:update]
  before_action :user_check, only: [:edit,:update]
  skip_before_action :login_required

  def new
     @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to timelines_path, notice: "会員登録が完了しました。"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  #アップデートアクション
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "会員情報を変更しました。"
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image,:image_cache)
  end

  def user_find
    @user= User.find(params[:id])
  end

  #ログインユーザが同一でない場合はトップページに戻るTrueを返す
  def user_check
    unless @user.id == current_user.id
      flash[:notice] = '編集できません'
      redirect_to timelines_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
   current_user.present?
  end

end

app/helpers/timelines_helper.rb
module TimelinesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_timelines_path
    elsif action_name == 'edit'
      timeline_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/timelines"> <%= image_tag('facebook.png') %></a>
        </div>

        <div class="collapse navbar-collapse navbar-right" id="navbarEexample1">
          <ul class="nav navbar-nav float-right">
            <% if current_user then %>
            <p class="navbar-text"><%= link_to "#{current_user.name}", user_path(current_user.id) %></p>
            <li><p class="navbar-text"><%= link_to "タイムライン", timelines_path %></p></li>
            <li ><p class="navbar-text"><%= link_to "新規投稿", new_timeline_path %></p></li>
            <li ><p class="navbar-text"><%= link_to "利用者リスト", relationships_path %></p></li>
            <li><p class="navbar-text"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></p></li>
            <% else %>
            <li ><p class="navbar-text"><%= link_to "新規登録", new_user_path %></p></li>
            <li ><p class="navbar-text"><%= link_to "ログイン", new_session_path %></p></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <div class="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/relationships/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <h4>利用者リスト</h4>
      <div class="relationship_table">
        <table class="table">
          <thead>
            <tr>
              <th class="col-md-4" scope="col">ユーザ名</th>
              <th class="col-md-4" scope="col">Email</th>
              <th class="col-md-4" scope="col">アクション</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <% if current_user.id == user.id then %>
              <% next %>
            <% end %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <% if current_user.friend?(user) then %>
              <td><%= link_to '友達解除', relationship_path(user.id), method: :delete ,data: { confirm: '友達登録を削除していいですか？' } %></td>
              <% else %>
              <td><%= form_with(model:@relationship, local: true) do |form| %>
                <%= form.hidden_field :id, :value => "#{user.id}" %>
                <div class="actions">
                  <%= form.submit "友達登録"%>
                </div>
              <% end %>
              </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/timelines/_form.html.erb
<%= form_with(model: timeline, local: true, url: choose_new_or_edit) do |form| %>
  <% if timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timeline.errors.count, "error") %> エラーが発生しました:</h2>
      <ul>
        <% timeline.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="row">
      <div class="form-group col-md-6">
        <label>タイトル</label>
        <input type="text" class="form-control" name="timeline[title]" value="<%=@timeline.title%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>内容</label>
        <textarea class="form-control" name="timeline[content]" rows="5"><%=@timeline.content%></textarea>
      </div>
    </div>

    <div class="form-row">
      <div class="timeline-image">
        <div class="form-group">
           <label>画像</label>
          <!-- 確認画面から新規作成画面に戻った時に、 -->
          <!-- アップロードした画像を表示させるための記述 -->
          <%= image_tag(@timeline.image.url) if @timeline.image && @timeline.image.url %>
          <%= form.file_field :image %>
          <%= form.hidden_field :image_cache %>
        </div>
      </div>
    </div>


    <button type="submit" class="btn btn-primary" name="commit">投稿する</button>
  </form>
<% end %>

app/views/timelines/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h4>以下の内容で、送信する。</h4>

        <%= form_with(model: @timeline, url: timelines_path, local: true) do |form| %>

          <%= form.hidden_field :title %>
          <%= form.hidden_field :content %>
          <%= form.hidden_field :image %>
          <%= form.hidden_field :image_cache %>

        <form>
            <div class="row">
              <div class="form-group col-md-6">
                <label>タイトル</label>
                <input type="text" readonly class="form-control" name="timeline[title]" value="<%=@timeline.title%>">
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-6">
                <label>内容</label>
                   <textarea readonly class="form-control" name="timeline[content]" rows="5"><%=@timeline.content%></textarea>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <label>画像</label>
                <div class="img-fluid">
                <%= image_tag(@timeline.image.url) if @timeline.image && @timeline.image.url %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-6">
                <label>ユーザ名</label>
                <input type="text" readonly class="form-control" name="timeline[title]" value="<%= @timeline.user.name %>">
                </div>
                </div>
            <button type="submit" class="btn btn-primary" name="commit">投稿する</button>
        <% end %>

        <%= form_with(model:@timeline, url:new_timeline_path, local:true, method:"get") do |form| %>
          <%= form.hidden_field :title %>
          <%= form.hidden_field :content %>
          <%= form.hidden_field :image %>
          <%= form.hidden_field :image_cache %>
          <button type="submit" class="btn btn-primary" name="back">戻る</button>
        <% end %>
        </form>
    </div>
  </div>
</div>

app/views/timelines/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h4>タイムラインの編集</h4>
        <%= render 'form', timeline: @timeline %>
        <a href="/timelines/<%=@timeline.id%>"><button class="btn btn-primary btn-sm" type="submit">詳細画面</button></a>
        <a href="/timelines"><button class="btn btn-primary  btn-sm" type="submit">タイムライン</button></a>
      </div>
    </div>
  </div>

app/views/timelines/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-2">
      <h4>サイドメニュー</h4>
      <div class="sidemenu">
        <ul>
          <a href="/users/<%=current_user.id %>">
            <li>
              <div class="sidemenu-img clearfix">
                <% if current_user.image.url then %>
                  <span><img src="<%=current_user.image%>" alt=""></span>
                <% end %>
              </div>
              <div class="sideitem">
                <span><%= current_user.name %></span>
              </div>
            </li>
          </a>
          <a href="/timelines/new">
            <li>
              <div class="sidemenu-img clearfix">
                <span><%= image_tag('timeline.jpg') %></span>
              </div>
              <div class="sideitem">
                タイムラインの投稿
              </div>
            </li>
          </a>
        </ul>
      </div>
    </div>

    <!-- タイムライン表示画面 -->
    <div class="col-md-8">
      <h4>投稿一覧</h4>
      <!-- つぶやき一覧を表示する -->
      <div class = "timelines">
        <% @timelines.each {|timeline| %>
          <div class="timeline">
            <div class="timeline-data clearfix">
              <div class="profile-img">
                <img src="<%=timeline.user.image%>" alt="">
              </div>
              <span class="timeline-title"><%= timeline.user.name %></span>
              <span class="create-date"><%= timeline.created_at %></span>
            </div>
            <div class="timeline-content">
              <p>タイトル : <%= timeline.title %></p>
              <p>内容: <%= timeline.content %></p>
            </div>
              <div class="timeline-img">
                <img src="<%=timeline.image%>" alt="" class="timeline-image">
              </div>
            <div class="timeline-edit clearfix">
              <%= link_to '詳細', timeline_path(timeline.id) %>
              <% if timeline.user.id == current_user.id then %>
                <%= link_to '編集', edit_timeline_path(timeline.id),data: { confirm: '本当に編集していいですか？' }  %>
                <%= link_to '削除', timeline_path(timeline.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
              <% end %>
            </div>
          </div>
        <% } %>
      </div>
    </div>

    <!-- 友達リスト表示 -->
    <div class="col-md-2">
      <h4>友達リスト</h4>
      <div class="sidemenu">
        <ul>
          <% current_user.friend.each do |user| %>
            <% if current_user.id == user.id then %>
              <% next %>
            <% end %>

            <a href="/users/<%=user.id%>">
              <li>
                <div class="friend-img clearfix">
                  <% if user.image.url then %>
                    <%= image_tag user.image.url %>
                  <% end %>
                </div>
                <div class="frien-name">
                  <%= user.name %>
                </div>
              </li>
            </a>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/timelines/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h4>タイムライン投稿</h4>
        <%= render 'form', timeline: @timeline %>
        <a href="/timelines"><button class="btn btn-primary" type="submit">戻る</button></a>
    </div>
  </div>
</div>

app/views/timelines/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class = "timelines">
        <div class="timeline">
          <div class="timeline-data clearfix">
            <div class="profile-img">
              <img src="<%=@timeline.user.image%>" alt="">
            </div>
            <span class="timeline-title"><%= @timeline.user.name %></span>
            <span class="create-date"><%= @timeline.created_at %></span>
          </div>
          <div class="timeline-content">
            <p>タイトル : <%= @timeline.title %></p>
            <p>内容: <%= @timeline.content %></p>
          </div>
          <div class="timeline-img">
            <img src="<%=@timeline.image%>" alt="" class="timeline-image">
          </div>
          <div class="timeline-edit clearfix">
            <%= link_to '詳細', timeline_path(@timeline.id) %>
            <% if @timeline.user.id == current_user.id then %>
              <%= link_to '編集', edit_timeline_path(@timeline.id),data: { confirm: '本当に編集していいですか？' }  %>
              <%= link_to '削除', timeline_path(@timeline.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model:user, local: true) do |f| %>

  <form>
    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <div class="form-row">
      <div class="form-group">
        <label>プロフィール画像</label>
        <div class="img-profile">
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
            <%= f.file_field :image %>
            <%= f.hidden_field :image_cache %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード</label>
        <input type="password" class="form-control" name="user[password]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード確認</label>
        <input type="password" class="form-control" name="user[password_confirmation]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-1">
        <button type="submit" class="btn btn-primary" name="commit">登録</button>
      </div>
    </div>
  </form>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h4>会員情報編集</h4>
  <%= render 'form', user: @user %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h4>会員登録</h4>
  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h4>ユーザ情報</h4>
  <form>
    <div class="row">
      <div class="col-md-6">
        <label>画像</label>
        <div class="img-profile">
          <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" readonly class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" readonly class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <% if @user.id == current_user.id then %>
      <%= link_to '編集', edit_user_path(@user) %> |
    <% end %>
    <%= link_to '戻る', timelines_path %>
  </form>
</div>